version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: garen
      POSTGRES_DB: database
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: 
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: garen
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
  frontend:
    build: 
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile  
    ports:
      - "3000:3001"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      REACT_APP_BACKEND_URL: http://backend:3000  # Changed from localhost to backend
    depends_on:
      - backend
    