version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database:/var/lib/postgresql/data
  backend:
    build: 
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
frontend:
  build: 
    context: ./frontend
    dockerfile: ../docker/frontend.dockerfile  # Replace with your Dockerfile name if different

    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
