version: "3.9"

services:
  frontend:
    build: ./frontend
    depends_on:
        - backend
    ports:
      - "3000:3000" 
    restart: always
    container_name: frontend
    networks:
      - mynetwork
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    container_name: backend
    restart: always
    networks:
      - mynetwork
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    container_name: database
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
