version: '3'
services:
  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      - /docker/db.env

  backend:
    build: 
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - /docker/backend.env
  frontend:
    build: 
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile  
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - ./docker/frontend.env
