version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: transcendence
      POSTGRES_PASSWORD: garen
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
  backend:
    build: 
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile  
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
